# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image.img_rc 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 499)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);font: 18pt Cascadia Code")
        self.main_win = QtWidgets.QWidget(MainWindow)
        self.main_win.setObjectName("main_win")
        self.text_edit = QtWidgets.QTextEdit(self.main_win)
        self.text_edit.setGeometry(QtCore.QRect(0, 0, 381, 501))
        self.text_edit.setStyleSheet("border-image: url(:/newPrefix/txt.PNG);padding:25px;")
        self.text_edit.setObjectName("text_edit")
        self.note_list = QtWidgets.QListWidget(self.main_win)
        self.note_list.setGeometry(QtCore.QRect(390, 30, 301, 131))
        self.note_list.setStyleSheet("border-image: url(:/newPrefix/list.PNG)")
        self.note_list.setObjectName("lable")
        self.txt_list = QtWidgets.QLabel(self.main_win)
        self.txt_list.setGeometry(QtCore.QRect(400, 0, 181, 21))
        self.txt_list.setObjectName("txt_list")
        self.teg_list = QtWidgets.QListWidget(self.main_win)
        self.teg_list.setGeometry(QtCore.QRect(390, 260, 301, 131))
        self.teg_list.setStyleSheet("border-image: url(:/newPrefix/list.PNG);")
        self.teg_list.setObjectName("lable_2")
        self.btn_add_note = QtWidgets.QPushButton(self.main_win)
        self.btn_add_note.setGeometry(QtCore.QRect(430, 180, 41, 31))
        self.btn_add_note.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-edit-3917361.png);")
        self.btn_add_note.setText("")
        self.btn_add_note.setObjectName("btn_add_note")
        self.btn_del_note = QtWidgets.QPushButton(self.main_win)
        self.btn_del_note.setGeometry(QtCore.QRect(520, 180, 41, 31))
        self.btn_del_note.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-trash-3917378.png);")
        self.btn_del_note.setText("")
        self.btn_del_note.setObjectName("btn_del_note")
        self.btn_dave_note = QtWidgets.QPushButton(self.main_win)
        self.btn_dave_note.setGeometry(QtCore.QRect(600, 180, 41, 31))
        self.btn_dave_note.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-check-3917749.png);")
        self.btn_dave_note.setText("")
        self.btn_dave_note.setObjectName("btn_dave_note")
        self.txt_list_2 = QtWidgets.QLabel(self.main_win)
        self.txt_list_2.setGeometry(QtCore.QRect(400, 230, 231, 20))
        self.txt_list_2.setObjectName("txt_list_2")
        self.teg_find = QtWidgets.QLineEdit(self.main_win)
        self.teg_find.setGeometry(QtCore.QRect(390, 400, 301, 30))
        self.teg_find.setStyleSheet("border:5px solid rgb(255, 253, 255);background-color: rgb(221, 255, 253);border-radius:15px;"
"")
        self.teg_find.setObjectName("teg_find")
        self.btn_del_teg = QtWidgets.QPushButton(self.main_win)
        self.btn_del_teg.setGeometry(QtCore.QRect(600, 440, 41, 31))
        self.btn_del_teg.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-cross-3917759.png);\n"
"")
        self.btn_del_teg.setText("")
        self.btn_del_teg.setObjectName("btn_del_teg")
        self.btn_find_teg = QtWidgets.QPushButton(self.main_win)
        self.btn_find_teg.setGeometry(QtCore.QRect(520, 440, 41, 31))
        self.btn_find_teg.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-search-3917132.png);")
        self.btn_find_teg.setText("")
        self.btn_find_teg.setObjectName("btn_find_teg")
        self.btn_add_teg = QtWidgets.QPushButton(self.main_win)
        self.btn_add_teg.setGeometry(QtCore.QRect(430, 440, 41, 31))
        self.btn_add_teg.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-user-add-3917698.png);")
        self.btn_add_teg.setText("")
        self.btn_add_teg.setObjectName("btn_add_teg")
        MainWindow.setCentralWidget(self.main_win)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Notes Edit"))
        self.txt_list.setText(_translate("MainWindow", "Список заміток"))
        self.txt_list_2.setText(_translate("MainWindow", "Список тегів"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
